name: CJS Library Build & Publish
 
trigger:
  tags:
    include:
      - 'release-*'
  branches:
    include:
      - main
  paths:
    include:
      - '*'
 
pr:
  - '*'
 
resources:
  repositories:
    - repository: cppAzureDevOpsTemplates
      type: github
      name: hmcts/cpp-azure-devops-templates
      endpoint: 'hmcts'
      ref: 'main'
 
    - repository: buildSettings
      type: github
      name: hmcts/cp-build-settings
      endpoint: 'hmcts'
      ref: 'main'
 
pool:
  name: 'MDV-ADO-AGENT-AKS-01'
  demands:
    - identifier -equals centos8-j17-postgres
 
variables:
  - name: sonarqubeProject
    value: "uk.gov.justice:framework-libraries"
  - group: "cjs-common-platform"

stages:
  - template: pipelines/cjscp-framework-build.yaml@cppAzureDevOpsTemplates
    parameters:
      sonarqube_project: ${{ variables['sonarqubeProject'] }}
      coveralls_repo_token: $(cp-framework-libraries)
